[package]
name = "workout-api-server"
version = "0.1.0"
authors = ["Nicholas Dujay <nickdujay@gmail.com>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
